// BOILERPLATE
export const BOILERPLATE_REQUEST = "BOILERPLATE_REQUEST" as const;
export const BOILERPLATE_SUCCESS = "BOILERPLATE_SUCCESS" as const;
export const BOILERPLATE_FAILURE = "BOILERPLATE_FAILURE" as const;
